# Generated by Django 2.2 on 2019-04-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default=False, verbose_name='ССылка на изображение'),
        ),
    ]
